package com.lu.persistence.dao;

import com.lu.model.Permission;
import com.lu.model.PermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_permission
     *
     * @mbggenerated Sat Mar 26 16:46:06 CST 2016
     */
    int countByExample(PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_permission
     *
     * @mbggenerated Sat Mar 26 16:46:06 CST 2016
     */
    int deleteByExample(PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_permission
     *
     * @mbggenerated Sat Mar 26 16:46:06 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_permission
     *
     * @mbggenerated Sat Mar 26 16:46:06 CST 2016
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_permission
     *
     * @mbggenerated Sat Mar 26 16:46:06 CST 2016
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_permission
     *
     * @mbggenerated Sat Mar 26 16:46:06 CST 2016
     */
    List<Permission> selectByExample(PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_permission
     *
     * @mbggenerated Sat Mar 26 16:46:06 CST 2016
     */
    Permission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_permission
     *
     * @mbggenerated Sat Mar 26 16:46:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") Permission record, @Param("example") PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_permission
     *
     * @mbggenerated Sat Mar 26 16:46:06 CST 2016
     */
    int updateByExample(@Param("record") Permission record, @Param("example") PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_permission
     *
     * @mbggenerated Sat Mar 26 16:46:06 CST 2016
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_permission
     *
     * @mbggenerated Sat Mar 26 16:46:06 CST 2016
     */
    int updateByPrimaryKey(Permission record);
}