package com.lu.persistence.dao;

import com.lu.model.RolePermissionRelExample;
import com.lu.model.RolePermissionRelKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolePermissionRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_permission_rel
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    int countByExample(RolePermissionRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_permission_rel
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    int deleteByExample(RolePermissionRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_permission_rel
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    int deleteByPrimaryKey(RolePermissionRelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_permission_rel
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    int insert(RolePermissionRelKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_permission_rel
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    int insertSelective(RolePermissionRelKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_permission_rel
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    List<RolePermissionRelKey> selectByExample(RolePermissionRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_permission_rel
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    int updateByExampleSelective(@Param("record") RolePermissionRelKey record, @Param("example") RolePermissionRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_permission_rel
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    int updateByExample(@Param("record") RolePermissionRelKey record, @Param("example") RolePermissionRelExample example);
}