package com.lu.persistence.dao;

import com.lu.model.RoleTaskRelExample;
import com.lu.model.RoleTaskRelKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleTaskRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_task_rel
     *
     * @mbggenerated Sun Apr 10 11:22:04 CST 2016
     */
    int countByExample(RoleTaskRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_task_rel
     *
     * @mbggenerated Sun Apr 10 11:22:04 CST 2016
     */
    int deleteByExample(RoleTaskRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_task_rel
     *
     * @mbggenerated Sun Apr 10 11:22:04 CST 2016
     */
    int deleteByPrimaryKey(RoleTaskRelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_task_rel
     *
     * @mbggenerated Sun Apr 10 11:22:04 CST 2016
     */
    int insert(RoleTaskRelKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_task_rel
     *
     * @mbggenerated Sun Apr 10 11:22:04 CST 2016
     */
    int insertSelective(RoleTaskRelKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_task_rel
     *
     * @mbggenerated Sun Apr 10 11:22:04 CST 2016
     */
    List<RoleTaskRelKey> selectByExample(RoleTaskRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_task_rel
     *
     * @mbggenerated Sun Apr 10 11:22:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") RoleTaskRelKey record, @Param("example") RoleTaskRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_role_task_rel
     *
     * @mbggenerated Sun Apr 10 11:22:04 CST 2016
     */
    int updateByExample(@Param("record") RoleTaskRelKey record, @Param("example") RoleTaskRelExample example);
}