package com.lu.model;

public class Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_permission.id
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_permission.name
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_permission.description
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_permission.task_id
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    private Long taskId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_permission.id
     *
     * @return the value of public.t_permission.id
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_permission.id
     *
     * @param id the value for public.t_permission.id
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_permission.name
     *
     * @return the value of public.t_permission.name
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_permission.name
     *
     * @param name the value for public.t_permission.name
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_permission.description
     *
     * @return the value of public.t_permission.description
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_permission.description
     *
     * @param description the value for public.t_permission.description
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_permission.task_id
     *
     * @return the value of public.t_permission.task_id
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_permission.task_id
     *
     * @param taskId the value for public.t_permission.task_id
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }
}