package com.lu.model;

import java.io.Serializable;

public class RoleTaskRelKey implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2775735068557018443L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column public.t_role_task_rel.role_id
	 *
	 * @mbggenerated Sun Apr 10 11:22:04 CST 2016
	 */
	private Integer roleId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column public.t_role_task_rel.task_id
	 *
	 * @mbggenerated Sun Apr 10 11:22:04 CST 2016
	 */
	private Integer taskId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column public.t_role_task_rel.role_id
	 *
	 * @return the value of public.t_role_task_rel.role_id
	 *
	 * @mbggenerated Sun Apr 10 11:22:04 CST 2016
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column public.t_role_task_rel.role_id
	 *
	 * @param roleId the value for public.t_role_task_rel.role_id
	 *
	 * @mbggenerated Sun Apr 10 11:22:04 CST 2016
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column public.t_role_task_rel.task_id
	 *
	 * @return the value of public.t_role_task_rel.task_id
	 *
	 * @mbggenerated Sun Apr 10 11:22:04 CST 2016
	 */
	public Integer getTaskId() {
		return taskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column public.t_role_task_rel.task_id
	 *
	 * @param taskId the value for public.t_role_task_rel.task_id
	 *
	 * @mbggenerated Sun Apr 10 11:22:04 CST 2016
	 */
	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}
}