package com.lu.model;

public class RolePermissionRelKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_role_permission_rel.role_id
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_role_permission_rel.permission_id
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    private Integer permissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_role_permission_rel.role_id
     *
     * @return the value of public.t_role_permission_rel.role_id
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_role_permission_rel.role_id
     *
     * @param roleId the value for public.t_role_permission_rel.role_id
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_role_permission_rel.permission_id
     *
     * @return the value of public.t_role_permission_rel.permission_id
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_role_permission_rel.permission_id
     *
     * @param permissionId the value for public.t_role_permission_rel.permission_id
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }
}