package com.lu.model;

public class Task {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_task.id
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_task.name
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_task.url
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_task.id
     *
     * @return the value of public.t_task.id
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_task.id
     *
     * @param id the value for public.t_task.id
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_task.name
     *
     * @return the value of public.t_task.name
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_task.name
     *
     * @param name the value for public.t_task.name
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_task.url
     *
     * @return the value of public.t_task.url
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_task.url
     *
     * @param url the value for public.t_task.url
     *
     * @mbggenerated Sun Mar 27 14:15:44 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}